[package]
name = "faser-executor"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
faser-task = { path = "../faser-task" }
futures-test = "0.3.29"

